on:
  push:
    branches:
      - master        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish python poetry package
      # You may pin to the exact commit or the version.
      # uses: JRubics/poetry-publish@a2294284dda5b857f4b41867a482fd1048a433f1
      uses: JRubics/poetry-publish@v1.2
      with:
        # API token to authenticate when uploading package to PyPI (https://pypi.org/manage/account/)
        pypi_token: ${{ secrets.PYPI_TOKEN }}
        repository_name: notify-me-tool 
